from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TiConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("taxii_url", models.URLField(blank=True, help_text="OpenCTI TAXII collection endpoint URL.")),
                ("request_timeout_seconds", models.PositiveIntegerField(default=30)),
                ("ioc_tag", models.CharField(default="opencti", max_length=64)),
                ("export_api_token", models.CharField(default="change-me", help_text="Bearer token required by the Wazuh manager fetch script. Change this before production.", max_length=255)),
                ("fetch_enabled", models.BooleanField(default=True)),
                ("fetch_cron_minute", models.CharField(default="0", max_length=64)),
                ("fetch_cron_hour", models.CharField(default="3,15", help_text="Default: twice per day.", max_length=64)),
                ("tranco_enabled", models.BooleanField(default=True)),
                ("tranco_dir", models.CharField(default="/var/lib/wazuh-ti/tranco", max_length=512)),
                ("tranco_max_age_days", models.PositiveIntegerField(default=14)),
                ("tranco_download_retries", models.PositiveIntegerField(default=3)),
                ("tranco_retry_sleep_seconds", models.PositiveIntegerField(default=5)),
                ("retrohunt_enabled", models.BooleanField(default=True)),
                ("retrohunt_queue_existing_on_first_run", models.BooleanField(default=False, help_text="False means first TAXII import creates the baseline but does not retro-hunt the whole existing inventory.")),
                ("opencti_initial_snapshot_seen", models.BooleanField(default=False, help_text="Internal flag. True after the first successful OpenCTI TAXII snapshot. Used to avoid retro-hunting the whole existing OpenCTI baseline on first import.")),
                ("retrohunt_interval_minutes", models.PositiveIntegerField(default=30)),
                ("retrohunt_index", models.CharField(default="wazuh-alerts-*", max_length=255)),
                ("retrohunt_lookback_days", models.PositiveIntegerField(default=90)),
                ("retrohunt_batches_per_run", models.PositiveIntegerField(default=4)),
                ("retrohunt_iocs_per_batch", models.PositiveIntegerField(default=250)),
                ("retrohunt_hash_iocs_per_batch", models.PositiveIntegerField(default=10)),
                ("retrohunt_page_size", models.PositiveIntegerField(default=100)),
                ("retrohunt_max_alerts_per_run", models.PositiveIntegerField(default=250)),
                ("retrohunt_query_delay_seconds", models.PositiveIntegerField(default=2)),
                ("retrohunt_hash_search_enabled", models.BooleanField(default=True)),
                ("wazuh_indexer_url", models.URLField(default="https://127.0.0.1:9200")),
                ("wazuh_indexer_username", models.CharField(blank=True, max_length=255)),
                ("wazuh_indexer_password", models.CharField(blank=True, max_length=255)),
                ("wazuh_indexer_verify_tls", models.BooleanField(default=False)),
                ("wazuh_indexer_ca_bundle", models.CharField(blank=True, max_length=512)),
                ("exact_ip_fields", models.TextField(default="data.src_ip\ndata.dest_ip\ndata.win.eventdata.sourceIp\ndata.win.eventdata.destinationIp")),
                ("exact_domain_fields", models.TextField(default="data.dns.rrname\ndata.tls.sni\ndata.http.hostname\ndata.win.eventdata.queryName")),
                ("hash_fields", models.TextField(default="data.win.eventdata.hashes\ndata.win.eventdata.hash")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "TI configuration", "verbose_name_plural": "TI configuration"},
        ),
        migrations.CreateModel(
            name="FetchRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("pending", "Pending"), ("running", "Running"), ("success", "Success"), ("failed", "Failed"), ("skipped", "Skipped")], db_index=True, default="pending", max_length=16)),
                ("triggered_by", models.CharField(default="scheduled", max_length=32)),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("total_objects", models.PositiveIntegerField(default=0)),
                ("total_indicators", models.PositiveIntegerField(default=0)),
                ("skipped_indicators", models.PositiveIntegerField(default=0)),
                ("ips", models.PositiveIntegerField(default=0)),
                ("domains", models.PositiveIntegerField(default=0)),
                ("hashes", models.PositiveIntegerField(default=0)),
                ("tranco_excluded_domains", models.PositiveIntegerField(default=0)),
                ("queued_retro_jobs", models.PositiveIntegerField(default=0)),
                ("log", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
            ],
            options={"ordering": ["-started_at"]},
        ),
        migrations.CreateModel(
            name="Indicator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("ip", "IP address"), ("domain", "Domain"), ("hash", "File hash")], db_index=True, max_length=16)),
                ("value", models.CharField(db_index=True, max_length=512)),
                ("source", models.CharField(db_index=True, default="opencti", max_length=64)),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("raw_indicator_id", models.CharField(blank=True, max_length=255)),
            ],
            options={"ordering": ["kind", "value"], "unique_together": {("kind", "value")}},
        ),
        migrations.CreateModel(
            name="RetroJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("ip", "IP address"), ("domain", "Domain"), ("hash", "File hash")], db_index=True, max_length=16)),
                ("value", models.CharField(db_index=True, max_length=512)),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                ("queued_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("batch_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("cursor", models.JSONField(blank=True, null=True)),
                ("last_attempt", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["-queued_at", "kind", "value"], "unique_together": {("kind", "value")}},
        ),
        migrations.CreateModel(
            name="RetroHuntRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("pending", "Pending"), ("running", "Running"), ("success", "Success"), ("failed", "Failed"), ("skipped", "Skipped")], db_index=True, default="pending", max_length=16)),
                ("triggered_by", models.CharField(default="scheduled", max_length=32)),
                ("manual_kind", models.CharField(blank=True, choices=[("ip", "IP address"), ("domain", "Domain"), ("hash", "File hash")], max_length=16)),
                ("manual_value", models.CharField(blank=True, max_length=512)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("batches", models.PositiveIntegerField(default=0)),
                ("iocs_tested", models.PositiveIntegerField(default=0)),
                ("hits", models.PositiveIntegerField(default=0)),
                ("emitted", models.PositiveIntegerField(default=0)),
                ("pending_after", models.PositiveIntegerField(default=0)),
                ("query_json", models.JSONField(blank=True, null=True)),
                ("result_json", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
            ],
            options={"ordering": ["-started_at"]},
        ),
        migrations.CreateModel(
            name="RetroHit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("ip", "IP address"), ("domain", "Domain"), ("hash", "File hash")], db_index=True, max_length=16)),
                ("value", models.CharField(db_index=True, max_length=512)),
                ("index_name", models.CharField(max_length=255)),
                ("document_id", models.CharField(max_length=255)),
                ("timestamp", models.CharField(blank=True, max_length=128)),
                ("agent_name", models.CharField(blank=True, max_length=255)),
                ("rule_id", models.CharField(blank=True, max_length=64)),
                ("rule_description", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=512)),
                ("decoder_name", models.CharField(blank=True, max_length=255)),
                ("matched_fields", models.TextField(blank=True)),
                ("raw_event", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="hit_rows", to="threatintel.retrohuntrun")),
            ],
            options={"ordering": ["-created_at"], "unique_together": {("kind", "value", "index_name", "document_id")}},
        ),
        migrations.AddIndex(model_name="indicator", index=models.Index(fields=["kind", "value"], name="ti_kind_value_idx")),
        migrations.AddIndex(model_name="indicator", index=models.Index(fields=["source", "last_seen"], name="ti_source_last_seen_idx")),
        migrations.AddIndex(model_name="retrojob", index=models.Index(fields=["kind", "queued_at"], name="ti_kind_queued_idx")),
        migrations.AddIndex(model_name="retrojob", index=models.Index(fields=["batch_id"], name="ti_batch_id_idx")),
        migrations.AddIndex(model_name="retrohit", index=models.Index(fields=["kind", "value"], name="ti_hit_kind_value_idx")),
        migrations.AddIndex(model_name="retrohit", index=models.Index(fields=["created_at"], name="ti_hit_created_idx")),
    ]
